### PR TITLE
support custom OutputAspectRatio

### PR DESCRIPTION
**Pull request by BrikerMan**
support set custom ratio with 
```
NextLevel.shared.videoConfiguration.aspectRatio = .custom(w: 2, h: 1)
```

### CODE REVIEW

**Comment by BrikerMan** [comment]
Thanks, this works perfectly for the video output. But here is an issue with `capturePhotoFromVideo`. It returns wrong aspect ratio. Maybe you can help me here.  https://github.com/NextLevel/NextLevel/issues/56#issuecomment-352983929

**Comment by piemonte** [comment]
🙌

**Comment by BrikerMan** [comment]
Any progress? @piemonte

**Comment by piemonte** [comment]
hey @BrikerMan – apologies, just saw your comment, will have to check it out when i get a free moment. unfortunately, i'm pretty slammed right now.

**Pull request merged**
